name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  Style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: [ 'src',  'test']
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format 
      uses: jidicula/clang-format-action@v4.10.1
      with:
        check-path: ${{ matrix.path }}

  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ['gcc', 'clang']
        mode: ['Debug', 'Release']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: https://github.com/OPM/eigen3
        path: eigen3
    
    - uses: lukka/get-cmake@latest
    
    - name: Install Eigen3
      run:  mkdir build && cd build && cmake .. && make install
    
    - if: ${{ matrix.compiler == 'gcc'  }}
      uses: egor-tensin/setup-gcc@v1
    - if: ${{ matrix.compiler == 'clang'  }}
      uses: egor-tensin/setup-clang@v1
    - run: |
       mkdir build && cd build &&
       cmake .. -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.mode }}

  Test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    - run: |
       mkdir build && cd build
       cmake ..
    - name: Run Test
      run: make test
